name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macOS-10.14, macos-10.15, macos-11.0]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1

      - name: Print Xcode version
        run: xcodebuild -version -sdk

      - name: Test
        run: xcodebuild -project Aware.xcodeproj -scheme Aware test ENABLE_HARDENED_RUNTIME=NO CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=
