name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - macos-11
          - macos-12
          - macos-13
          - macos-14

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: Print Xcode version
        run: xcodebuild -version -sdk

      - name: Test
        run: xcodebuild -project Aware.xcodeproj -scheme Aware test ENABLE_HARDENED_RUNTIME=NO CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=
